name: Select or Create Terraform Workspace (PreProd)

       id: workspace_preprod

       run: |

        WORKSPACE_NAME="preprod-workspace"

        ORGANIZATION="your-terraform-org"

        

         # Query Terraform Cloud API for workspace details

         WORKSPACE_ID=$(curl -sS --header "Authorization: Bearer $TFC_API_TOKEN" \

                       --header "Content-Type: application/vnd.api+json" \

                       "https://app.terraform.io/api/v2/organizations/$ORGANIZATION/workspaces?filter[name][$eq]=$WORKSPACE_NAME" | jq -r '.data[0].id')

 

         if [ -z "$WORKSPACE_ID" ]; then

           echo "Workspace $WORKSPACE_NAME not found."

           exit 1

         fi

 

         echo "::set-output name=workspace_id::$WORKSPACE_ID"

 

     - name: Deploy Terraform Infrastructure to PreProd

       run: |

         # Use the selected workspace_id from previous step

         terraform workspace select ${{ steps.workspace_preprod.outputs.workspace_id }}

         terraform init
