name: Retrieve and Print Terraform Workspaces

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TF_API_TOKEN: ${{ secrets.TFC_API_TOKEN }}
  TF_ORG: "your-terraform-cloud-organization"

jobs:
  retrieve-workspaces:
    name: Retrieve Terraform Workspaces
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Terraform Cloud credentials
        run: echo "credentials \"app.terraform.io\" { token = \"${{ env.TF_API_TOKEN }}\" }" > $HOME/.terraformrc

      - name: Retrieve Workspaces
        id: get_workspaces
        run: |
          ORGANIZATION="Mlops_Amani"
          
          RESPONSE=$(curl -sS \
            --header "Authorization: Bearer ${{ env.TF_API_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            "https://app.terraform.io/api/v2/organizations/Mlop_Amani/workspaces")

          echo $RESPONSE | jq '.data[] | {id: .id, name: .attributes.name}'

          echo "::set-output name=workspaces::$RESPONSE"

      - name: Print Workspaces
        run: |
          echo "Retrieved Workspaces:"
          echo "${{ steps.get_workspaces.outputs.workspaces }}" | jq '.data[] | "\(.attributes.name): \(.id)"'
