name: List Terraform Cloud Workspaces

on:
  push:
    branches:
      - main

jobs:
  list-workspaces:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Terraform CLI
        run: |
          mkdir ~/.terraform.d
          echo '{ "credentials": { "app.terraform.io": { "token": "${{ secrets.TF_API_TOKEN }}" } }, "provider": { "app.terraform.io": { "organization": "${{ secrets.TF_ORGANIZATION }}" } } }' > ~/.terraform.d/credentials.tfrc.json
        
      - name: Initialize Terraform
        run: terraform init
        
      - name: List Workspaces
        run: |
          workspaces=$(terraform workspace list -json | jq -r '.[]')
          echo "Terraform Cloud Workspaces:"
          echo "$workspaces"
