name: Retrieve and Print Terraform Workspaces

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TF_API_TOKEN: ${{ secrets.TFC_API_TOKEN }}
  TF_ORG: "your-terraform-cloud-organization"

jobs:
  retrieve-workspaces:
    name: Retrieve Terraform Workspaces
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Terraform Cloud credentials
        run: echo "credentials \"app.terraform.io\" { token = \"${{ env.TF_API_TOKEN }}\" }" > $HOME/.terraformrc

      - name: Retrieve Workspaces
        id: get_workspaces
        run: |
          WORKSPACE_NAME="preprod-workspace"
          ORGANIZATION="your-terraform-org

         # Query Terraform Cloud API for workspace details
        WORKSPACE_ID=$(curl -sS --header "Authorization: Bearer $TFC_API_TOKEN" \

                       --header "Content-Type: application/vnd.api+json" \

                       "https://app.terraform.io/api/v2/organizations/$ORGANIZATION/workspaces?filter[name][$eq]=$WORKSPACE_NAME" | jq -r '.data[0].id')

 

         if [ -z "$WORKSPACE_ID" ]; then

           echo "Workspace $WORKSPACE_NAME not found."

           exit 1

         fi
      - name: Print Workspaces
        run: |
          echo "Retrieved Workspaces:"
          echo "${{ steps.get_workspaces.outputs.workspaces }}" | jq '.data[] | "\(.attributes.name): \(.id)"'
