name: Retrieve Terraform Workspace ID

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_ORG: "Mlops_Amani"
  WORKSPACE_NAME: "tfc_re_bootstrap"

jobs:
  retrieve-workspace-id:
    name: Retrieve Terraform Workspace ID
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Terraform Cloud credentials
        run: echo "credentials \"app.terraform.io\" { token = \"${{ env.TF_API_TOKEN }}\" }" > $HOME/.terraformrc

      - name: Retrieve Workspace ID
        id: get_workspace_id
        run: |
          ORGANIZATION="${{ env.TF_ORG }}"
          WORKSPACE_NAME="${{ env.WORKSPACE_NAME }}"

          # Query Terraform Cloud API for workspace details
          RESPONSE=$(curl -sS \
            --header "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            "https://app.terraform.io/api/v2/organizations/$ORGANIZATION/workspaces?filter[name][$eq]=$WORKSPACE_NAME")

          WORKSPACE_ID=$(echo $RESPONSE | jq -r '.data[0].id')

          if [ -z "$WORKSPACE_ID" ]; then
            echo "Workspace $WORKSPACE_NAME not found."
            exit 1
          fi

          echo "::set-output name=workspace_id::$WORKSPACE_ID"

      - name: Print Workspace ID
        run: |
          echo "Retrieved Workspace ID:"
          echo "${{ steps.get_workspace_id.outputs.workspace_id }}"
